### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by oyeanuj** [kvendrik/intercom-react#8] opened 2018-08-22 18:29 UTC
Hi @kvendrik! As I was playing with this, I am seeing errors on the server side since the `window` object is not available on the server:
```
SERVER: ERROR in server execution:
ReferenceError: window is not defined
```

I assume a check is needed to see if the `window` object is defined and if not, aborting early?

**Comment by kvendrik** [comment] 2018-08-22 18:46
Hey @oyeanuj! Hmm interesting as the component [doesn't seem to use `window` anywhere](https://github.com/kvendrik/intercom-react/search?q=window&unscoped_q=window) except for [within the frame](https://github.com/kvendrik/intercom-react/blob/master/Intercom/components/ImportIsolatedRemote/ImportIsolatedRemote.tsx#L26).

I currently don't have time to contribute to the component but [as mentioned in the other issue](https://github.com/kvendrik/intercom-react/issues/5#issuecomment-415138006): if you'd like to use this feel free to contribute. 🙂

**Comment by oyeanuj** [comment] 2018-08-22 18:57
Thanks for the quick response! I think the `window` object might be used by the Intercom API itself. The `react-intercom` component has a check to see if DOM can be used before proceeding further: 

https://github.com/nhagen/react-intercom/blob/913b41107c43fc942f27b7cb7f6a0a575eb913b0/src/index.js#L3

**Comment by kvendrik** [comment] 2018-08-22 19:02
I feel like in their case the check is mainly there because they're directly referencing `window.Intercom` whereas we wait until the iframe has been loaded. I might be wrong though and I wonder where the `window` reference that is throwing the error in our case lives.

**Comment by kvendrik** [comment] 2019-06-20 18:31
Update: the library [doesn't reference `window` anywhere directly](https://github.com/kvendrik/intercom-react/search?q=window&unscoped_q=window), therefor I'm not sure this is caused by the library. I'll close the issue for now, if more SSR issues pop up we can reopen it.

**Closed** 2019-06-20 18:32 UTC
Labels: enhancement
